<?php

namespace Database\Seeders;

use App\Models\Imagen;
use App\Models\Producto;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

      $productos= [
        [
          'nombre' => 'producto 1',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111111',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 2',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111112',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '10',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 3',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111113',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '50',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 4',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111114',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 5',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111115',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 6',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111116',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 7',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111117',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 8',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111118',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 9',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111119',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 10',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '1111111110',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 11',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '11111111111',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 12',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '111111111112',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 13',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '111111111113',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 14',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '111111111114',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 15',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '111111111115',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
        [
          'nombre' => 'producto 16',
          'precio_entrada' => '200',
          'precio_letal' => '220',
          'precio_mayor' => '210',
          'cod_barra' => '111111111116',
          'estado' => 'Habilitado',
          'cantidad' => '50',
          'observaciones' => 'sin observaciones',
          'presentacion' => 'Unidad',
          'stock_minimo' => '15',
          'vencimiento' => 'No',
          'tipo_garantia' => 'N/A',
          'categoria_id' => '1',
          'modelo_id' => '1',
          'marca_id' => '1',
        ],
      ];

      foreach ($productos as $producto){
        Producto::create($producto);
     }



  

        // Imagen::factory(1)->create([
        //     'imageable_id'=> '1',
        //     'imageable_type'=>Producto::class
        // ]);
    }
}
