<?php

namespace Database\Seeders;

use App\Models\Producto_lote;
use Illuminate\Database\Seeder;

class ProductoLoteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productos_lotes=[
            [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '1',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '1',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '2',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '3',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '4',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '5',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '6',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '6',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '7',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '7',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '8',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '8',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '9',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '9',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '10',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '10',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '11',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '11',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '12',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '12',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '13',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '2',
                'proveedor_id' => '1',
                'producto_id' => '13',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '25',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '14',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '15',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '16',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '17',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '18',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '19',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
              [
                'lote' => '1',
                'proveedor_id' => '1',
                'producto_id' => '20',
                'precio_entrada' => '200',
                'precio_letal' => '220',
                'precio_mayor' => '210',
                'utilidad_letal' => '20',
                'utilidad_mayor' => '10',
                'margen_letal' => '9.10',
                'margen_mayor' => '4.8',
                'stock' => '50',
                'observaciones' => 'sin observaciones',
              ],
            ];
        foreach ($productos_lotes as $producto_lote){
            Producto_lote::create($producto_lote);
        }
    }
}
